const dummyData = [
  {
    id: 1,
    title: 'The Feynman Lectures on Physics',
    author: 'Richard P. Feynman',
    genre: 'Physics',
    description: 'A series of lectures by Nobel Prize-winning physicist Richard P. Feynman. Dive into the fascinating world of physics with one of the greatest minds in the field.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1299.99,
  },
  {
    id: 2,
    title: 'The Code Book',
    author: 'Simon Singh',
    genre: 'Programming',
    description: 'Unlock the secrets of codes and ciphers throughout history. From ancient techniques to modern encryption methods, explore the intriguing world of cryptography.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 799.99,
  },
  {
    id: 3,
    title: 'Chemistry: The Central Science',
    author: 'Theodore L. Brown, H. Eugene LeMay Jr., Bruce E. Bursten',
    genre: 'Chemistry',
    description: 'Embark on a journey through the central science of chemistry. Understand the principles that govern matter, reactions, and the composition of substances.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1099.99,
  },
  {
    id: 4,
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
    genre: 'Programming',
    description: 'A comprehensive guide to algorithms, a cornerstone in computer science. Master the art of designing and analyzing algorithms for efficient problem-solving.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 899.99,
  },
  {
    id: 5,
    title: 'Astrophysics for Young People in a Hurry',
    author: 'Neil deGrasse Tyson',
    genre: 'Physics',
    description: 'Neil deGrasse Tyson breaks down the complexities of astrophysics for young readers. Explore the wonders of the cosmos in an engaging and accessible way.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1299.99,
  },
  {
    id: 6,
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    genre: 'Programming',
    description: 'Become a master of writing clean and maintainable code. Robert C. Martin shares principles and practices for software craftsmanship.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 699.99,
  },
  {
    id: 7,
    title: 'Organic Chemistry: Structure and Function',
    author: 'K. Peter C. Vollhardt, Neil E. Schore',
    genre: 'Chemistry',
    description: 'Explore the intricacies of organic chemistry. Understand the structure and function of organic compounds in this comprehensive guide.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1199.99,
  },
  {
    id: 8,
    title: 'The C Programming Language',
    author: 'Brian W. Kernighan, Dennis M. Ritchie',
    genre: 'Programming',
    description: 'The classic book that introduced the world to the C programming language. Learn the foundations of one of the most influential programming languages.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 999.99,
  },
  {
    id: 9,
    title: 'Physics of the Impossible',
    author: 'Michio Kaku',
    genre: 'Physics',
    description: 'Join Michio Kaku on a journey into the realm of the impossible. Explore concepts like time travel, teleportation, and parallel universes in this captivating exploration.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1399.99,
  },
  {
    id: 10,
    title: 'Data Science for Business',
    author: 'Foster Provost, Tom Fawcett',
    genre: 'Programming',
    description: 'Bridge the gap between data science and business decisions. Foster Provost and Tom Fawcett provide insights into leveraging data for strategic decision-making.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 899.99,
  },
  {
    id: 11,
    title: 'Inorganic Chemistry',
    author: 'Gary L. Miessler, Paul J. Fischer, Donald A. Tarr',
    genre: 'Chemistry',
    description: 'Delve into the principles of inorganic chemistry. Gain a deep understanding of the structure and behavior of inorganic compounds.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1299.99,
  },
  {
    id: 12,
    title: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    genre: 'Programming',
    description: 'Learn JavaScript in an eloquent and engaging way. Marijn Haverbeke takes you through the fundamental concepts and features of the language.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 749.99,
  },
  {
    id: 13,
    title: 'Black Holes and Time Warps',
    author: 'Kip S. Thorne',
    genre: 'Physics',
    description: 'Embark on a fascinating journey into the mysteries of black holes and the fabric of spacetime. Kip S. Thorne guides you through the wonders of the universe.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1099.99,
  },
  {
    id: 14,
    title: 'Machine Learning Yearning',
    author: 'Andrew Ng',
    genre: 'Programming',
    description: 'Guidance for machine learning practitioners on building effective systems. Andrew Ng shares insights and strategies for successful machine learning projects.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1199.99,
  },
  {
    id: 15,
    title: 'Biochemistry',
    author: 'Donald Voet, Judith G. Voet, Charlotte W. Pratt',
    genre: 'Chemistry',
    description: 'Explore the fundamental principles of biochemistry and their applications. Donald Voet, Judith G. Voet, and Charlotte W. Pratt provide a comprehensive overview.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 949.99,
  },
  {
    id: 16,
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt, David Thomas',
    genre: 'Programming',
    description: 'Embark on your journey to mastery with this classic book on programming. Andrew Hunt and David Thomas share practical advice for effective software development.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1049.99,
  },
  {
    id: 17,
    title: 'Seven Brief Lessons on Physics',
    author: 'Carlo Rovelli',
    genre: 'Physics',
    description: 'Experience the beauty and wonder of physics in seven brief lessons. Carlo Rovelli provides a poetic exploration of the universe and its mysteries.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 799.99,
  },
  {
    id: 18,
    title: 'Dive into Python 3',
    author: 'Mark Pilgrim',
    genre: 'Programming',
    description: 'Immerse yourself in the world of Python 3 with this comprehensive guide. Mark Pilgrim provides insights and examples for mastering the Python programming language.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1399.99,
  },
  {
    id: 19,
    title: 'Quantum Mechanics: Concepts and Applications',
    author: 'Nouredine Zettili',
    genre: 'Physics',
    description: 'Gain a deep understanding of quantum mechanics and its practical applications. Nouredine Zettili explores the concepts that shape the quantum world.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 999.99,
  },
  {
    id: 20,
    title: 'Web Development with Node.js and Express',
    author: 'Ethan Brown',
    genre: 'Programming',
    description: 'Learn web development using Node.js and Express. Ethan Brown guides you through building scalable and efficient web applications.',
    coverImage: 'https://images-cdn.ubuy.co.in/63a1eebf47b33059b3084aef-the-feynman-lectures-on-physics-vol.jpg',
    price: 1199.99,
  },
];

export default dummyData;
